/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestGradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class TestFunctionClass {
    @Test public void testFunctionClass_1and5_6() {
    	IFunctionClass classUnderTest = new FunctionClass();
        assertEquals(6, classUnderTest.sum(1, 5));
    }
}
